name: Frontend Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

env:
  REACT_APP_MOVIE_API_URL: http://localhost:5000
  AWS_REGION: us-east-1
  ECR_REGISTRY: 607049766878.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO: frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test_job:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/cache@v3
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: cd starter/frontend && npm ci
      - run: cd starter/frontend && CI=true npm test

  lint_job:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/cache@v3
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: cd starter/frontend && npm ci && npx eslint . --fix

  build:
    needs: [test_job, lint_job]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG . --build-arg="REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL"
          echo "docker build is success"
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          echo $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name cluster

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Debug the directory
        run: |
          echo "Checking directory structure"
          ls -R starter/frontend/k8s

      - name: Set Image Tag in Kustomize
        run: |
          echo "ECR Registry: ${{ env.ECR_REGISTRY }}"
          echo "ECR Repo: ${{ env.ECR_REPO }}"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"
          cd starter/frontend/k8s
          kustomize edit set image frontend=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Apply Kubernetes Manifests
        run: |
          cd starter/frontend/k8s
          kustomize build | kubectl apply -f - --validate=false

